spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/buildup?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(HB+BkYU7fCeSlhYumIHr8sTj5V6tgTNvCTcjT9zSbXvnyJ52UUy7Zla8VE2xU1MCwjrljQP5emw3Joru1EQDy3alMHf1ry6Wztphd/BLzfFFSy1zlNH2C/90es9Y275U1Ghp3jLWif9dtQMRquPyS5ojpe0bA+IMmOdYPl+lCWXUl096BMyiP4F2LjbY8G70JWsfIwCmA83bADdUxZEkOohdDePoABF7wMIhmmqFtLPJMK4hRMf3RNWyxjcm5bl8vHiC8ZQxp2hnIMcp/1kiEA==)
    username: ENC(AbBUeOQseTvNxj0o/TE0SQ==)
    password: ENC(u5ytEEG40z8d8uXIu5p9Gfb8Zwmj89ldwXQAgupLu5k=)
    driver-class-name: com.mysql.cj.jdbc.Driver