spring:
  config:
    activate:
      on-profile: local
  redis:
    port: 6379
    host: localhost
    password:

---
spring:
  config:
    activate:
      on-profile: dev
  redis:
    port: 6379
    password:
    host:
