spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/buildup?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(80vjjoFrw+JFe2P+4I7KSu+sErvcnedbz9elsH+9imQ0UfdmfMNfSAP7tC+xJOhMp/uf94+WSZWEN07wjpZ6yVPkgAox2KhhtXugBaYFfOdVLx+QjZgrRnUe0/qUSFG9/FIQz/GyiMcFYuuwg5k3qEopoDVGe72/NSodV+KytUF0sDCOeyk7SMBagWvGUF++F7rMw7KD8V0CmI+OK62P0GT8Z6haEn/LacRzSOjy0L/+YBV5EbHmMEFDqAzotvrBlSnOqejjsv+vInHqRFxT+nfyKFll/KHx)
    username: ENC(xLnpevwl7rt89CRTP8dedg==)
    password: ENC(vWLmaIfpeq00UE8/uUOSA756l9Rm+eM/GAvXuU2HInE=)
    driver-class-name: com.mysql.cj.jdbc.Driver