server:
  port: 9000
spring:
  application:
    name: buildup
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - redis
      - jasypt
      - mysql
      - swagger
    active: local